routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/', function(){
    return redirect(route('login'));
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::delete('crates', 'CrateController@clear_crate')->name('crates.clear');

Route::resource('categories', 'CategoryController');
Route::resource('items', 'ItemController');
Route::resource('crates', 'CrateController');
Route::resource('borrow_requests', 'BorrowRequestController');

app/Http/Controllers/CrateController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Item;
use Session;

class CrateController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $this->authorize('isLogged');

        if(Session::has('crate')){
            $item_ids = array_keys(Session::get('crate'));

            //fetch items
            $items = Item::find($item_ids);
            
            return view('crates.index')->with('items', $items);
        }

        return view('crates.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        $this->authorize('isLogged');

        //
        // dd($request->session()->all());
        // dd($request->input('id'));

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->authorize('isLogged');

        $request->validate([
            'id'=>'required',
            'borrow-date'=>'date',
            'return-date'=>'date',
        ]);

        // crate format

        // borrow request id
        // item id => borrow date
        // item_id => return date

        // $cart = [
        //     id => [
        //         borrow-date => date,
        //         return-date => date
        //     ]
        // ]
        // $item = Item::find($id);

        $id = $request->input('id');
        $borrow_date = $request->input('borrow-date');
        $return_date = $request->input('return-date');

        $request->session()->put("crate.$id", [
                'borrow-date' => $borrow_date,
                'return-date' => $return_date
            ]);

        return redirect(route('crates.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
        $this->authorize('isLogged');

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $this->authorize('isLogged');

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $this->authorize('isLogged');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        $this->authorize('isLogged');
        
        // dd($id);
        Session::forget("crate.$id");

        return redirect(route('crates.index'));
    }

    public function clear_crate(){

        Session::forget('crate');
        
        return redirect(route('crates.index'))->with('info', 'Crate is cleared.');
    }
}

resources/views/crates/index.blade.php
@extends('layouts.app')

@section('content')
{{-- {{ dd(Session::get('crate')) }} --}}
<h3 class="text-center">{{Auth::user() ? Auth::user()->name."'s Crate" : 'Your Crate'}}</h3>
<div class="row">
	<div class="col-12">
		@if(Session::has('crate') && count(Session::get('crate')))
		<table class="table table-hover">
			<thead>
				<tr>
					<th>Name</th>
					<th>Serial #</th>
					<th>Borrow Date and Time</th>
					<th>Return Date and Time</th>
					<th>Action</th>
				</tr>
			</thead>
			<tbody>
				{{-- {{dd(Session::get('crate'))}} --}}
				@foreach($items as $item)
				<tr>
					<td>{{ $item->brand_name . ' ' . $item->model_name }}</td>
					<td>{{ $item->serial_number }}</td>
					<td>{{ Session::get("crate.$item->id")["borrow-date"] }}</td>
					<td>{{ Session::get("crate.$item->id")["return-date"] }}</td>
					<td>
						<form action="{{ route('crates.destroy', $item->id) }}" method="POST">
							@csrf
							@method('DELETE')
							<button class="btn btn-danger btn-sm">Remove</button>
						</form>
					</td>
				</tr>
				@endforeach
			</tbody>
			<tfoot>
				<tr>
					<td>
						<form action="{{ route('borrow_requests.store') }}" method="POST"> 
							@csrf
							<button class="btn btn-success">Finalize Crate</button>
						</form>
					</td>
					<td>
						<form action="{{ route('crates.clear') }}" method="POST">
							@csrf
							@method('DELETE')
							<button class="btn btn-danger" type="submit">Clear Crate</button>
						</form>
					</td>
					<td></td>
					<td></td>
					<td></td>
				</tr>
			</tfoot>
		</table>
		@else
			<h3>Your crate is empty.</h3>
		@endif
		
	</div>
</div>

@endsection