routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/', function(){
    return redirect(route('login'));
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::delete('crates', 'CrateController@clear_crate')->name('crates.clear');

Route::resource('categories', 'CategoryController');
Route::resource('items', 'ItemController');
Route::resource('crates', 'CrateController');
Route::resource('borrow_requests', 'BorrowRequestController');

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $fillable = ['name'];


    public function items(){
    	return $this->hasMany('App\Item');
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $this->authorize('isAdmin');
        return view('categories.index')->with('categories', Category::all());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $this->authorize('isAdmin');
        return view('categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->authorize('isAdmin');
        $request->validate([
            'name' => 'required|unique:categories'
        ]);

        Category::create([
            'name' => $request->input('name')
        ]);

        $request->session()->flash('success','Categery added successfully.');

        return redirect(route('categories.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {
        $this->authorize('isLogged');
        
        // return view('categories.show')->with('category', $category);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        $this->authorize('isAdmin');
        return view('categories.create')->with('category', $category);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Category $category)
    {
        $this->authorize('isAdmin');
        $request->validate([
            'name' => 'required|unique:categories,name'
        ]);

        $category->update([
            'name' => $request->input('name')
        ]);

        $request->session()->flash('success','Categery updated successfully.');

        return redirect(route('categories.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        $this->authorize('isAdmin');
        $category->delete();

        // $request->session()->flash('success','Categery deleted successfully.');

        return redirect(route('categories.index'))->with('message', "deleted")->with('info', 'Category deleted successfully.');
    }
}

resources/views/categories/create.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
    @if(Session::has('success'))
        <div class="alert alert-success">{{ Session::get('success') }}</div>
    @endif

    <h1 class="text-center">
    {{ isset($category) ? "Edit Category" : "Add Category" }}
    </h1>
    <div class="row">
        <div class="col-12 col-md-12 mx-auto">    
            <form action="{{ isset($category) ? route('categories.update',['category'=>$category->id]) : route('categories.store') }}" method="POST">
                @csrf
                @if(isset($category))
                    @method('PUT')
                @endif
                <div class="form-group">
                    <label for="name">Name:</label>
                    <input type="text" name="name" id="name" class="form-control
                    @if($errors->has('name'))
                    is-invalid
                    @endif
                    " value="{{
                        isset($category) ? $category->name : ''
                    }}">
                    <div class="invalid-feedback">{{ $errors->first('name') }}</div>
                </div>

                <button type="submit" class="btn btn-success">{{ isset($category) ? "Update" : "Add Category" }}</button>
            </form>
        </div>
    </div>
</div>

@endsection

resources/views/categories/index.blade.php
@extends('layouts.app')

@section('content')

@if($errors->any())
    dd($errors->first())
@endif

<div class="container">
    <h1 class="text-center">Category List</h1>
        <div class="row">
            <div class="col-12 col-md-8 mx-auto">
            <div class="d-flex justify-content-end mb-3">
                <a class="btn btn-success" href="{{ route('categories.create') }}">Add Category</a>
            </div>

            @if($categories->count()>0)
            <table class="table table-hover">
                <tbody>
                    @foreach($categories as $category )
                    <tr>
                        <td>{{ $category->name }}</td>
                        <td class="text-center"><a href="{{ route('categories.edit',['category'=>$category->id]) }}" class="btn btn-info btn-sm">Edit</a></td>
                        <td class="text-center">
                        <form action="{{ route('categories.destroy',['category'=>$category->id]) }}" method="POST">
                            @csrf
                            @method("DELETE")
                            <button class="btn btn-danger btn-sm">Delete</button>
                        </form>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
            @else
            <h4>No categories yet.</h4>
            @endif


            </div>
        </div>
</div>

@endsection