routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/', function(){
    return redirect(route('login'));
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::delete('crates', 'CrateController@clear_crate')->name('crates.clear');

Route::resource('categories', 'CategoryController');
Route::resource('items', 'ItemController');
Route::resource('crates', 'CrateController');
Route::resource('borrow_requests', 'BorrowRequestController');

app/Item.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Item extends Model
{
    protected $fillable = [
        'brand_name',
        'model_name',
        'category_id',
        'serial_number',
        'image',
        'item_status_id',
        'description'
    ];

    public function category(){
        return $this->belongsTo('App\Category');
    }

    public function item_status(){
        return $this->belongsTo('App\Item_status');
    }

    public function borrow_requests(){
        return $this->belongsToMany('App\Borrow_request','item_borrow_request')
            ->withPivot('is_return','start_date', 'return_date')
            ->withTimestamps();
    }


}

app/Http/Controllers/ItemController.php
<?php

namespace App\Http\Controllers;

use App\Item;
use App\Item_status;
use App\Category;
use Illuminate\Http\Request;
use Str;
use Storage;
use Auth;

class ItemController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $this->authorize('isLogged');
        // dd($request->url());
        if(Auth::user() && Auth::user()->role_id === 1) {
            if($request->query()){
                $items = Item::where('category_id', $request->query('category'))->get();
            } else {
                $items = Item::all();
            }
            return view('items.index')->with('items', $items)->with('categories', Category::all());
        } else {
            return view('items.index')->with('items', Item::all()->where('item_status_id', 1));
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $this->authorize('isAdmin');

        return view('items.create')
            ->with('item_statuses', Item_status::all())
            ->with('categories', Category::all());
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->authorize('isAdmin');

        //validation
        $request->validate([
            'brand-name' => 'required|string',
            'model-name' => 'required|string',
            'category' => 'string',
            'serial-number'=>'required|unique:items,serial_number',
            'image'=> 'file|image|mimes:jpeg,jpg,png|max:2000',
            'item-status' => 'string',
            'description' => 'string'
        ]);

        $file_path=''; //set default image

        if($request->hasFile('image')){
            // get image path before saving
            $file = $request->file('image');
            $file_name = pathinfo($file->getClientOriginalName(), PATHINFO_FILENAME);
            $file_extenstion = $file->extension();
            $random_char = Str::random();
            $new_file_name = date('Y-m-d-H-i-s') . '_' . $random_char . '_' . $file_name . '.' . $file_extenstion;
            $file_path = $file -> storeAs('images', $new_file_name, 'public');
        };

        // save to db
        Item::create([
            'brand_name' => $request->input('brand-name'),
            'model_name' => $request->input('model-name'),
            'category_id' => $request->input('category'),
            'serial_number' => $request->input('serial-number'), 
            'item_status_id' => $request->input('item-status'),
            'description' => $request->input('description'),
            'image' => $file_path
        ]);

        $request->session()->flash('success', 'Item added successfully.');

        return redirect(route('items.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Item  $item
     * @return \Illuminate\Http\Response
     */
    public function show(Item $item)
    {
        //
        return view('items.show')->with('item', $item);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Item  $item
     * @return \Illuminate\Http\Response
     */
    public function edit(Item $item)
    {
        $this->authorize('isAdmin');

        // dd($item);
        return view('items.create')
            ->with('item', $item)
            ->with('categories', Category::all())
            ->with('item_statuses', Item_status::all());
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Item  $item
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Item $item)
    {
        $this->authorize('isAdmin');

         //validation
        $request->validate([
            'brand-name' => 'required|string',
            'model-name' => 'required|string',
            'category' => 'string',
            'serial-number'=>'required',
            'item-status' => 'string',
            'description' => 'required',
            'image'=> 'file|image|mimes:jpeg,jpg,png|max:2000'

        ]);


        if(
            !$request->hasFile('image') &&
            $item->brand_name == $request->input('brand-name') &&
            $item->model_name == $request->input('model-name') &&
            $item->description == $request->input('description') &&
            $item->category_id == $request->input('category') &&
            $item->item_status_id == $request->input('item-status') &&
            $item->serial_number == $request->input('serial-number')
        ){

            $request->session()->flash('info', 'No changes has been made.');

            return redirect(route('items.edit', ['item'=>$item->id]));
        } else {

            // update the entry in the database and return the updated entry
            
            // check if there's a file uploaded
            if ($request->hasFile('image')) {
                // $request->validate([
                    //     'image'=> 'file|image|mimes:jpeg,jpg,png|max:2000'
                    // ]);

                $file = $request->file('image');
                $file_name = pathinfo($file->getClientOriginalName(), PATHINFO_FILENAME);
                $file_extenstion = $file->extension();
                $random_char = Str::random();
                $new_file_name = date('Y-m-d-H-i-s') . '_' . $random_char . '_' . $file_name . '.' . $file_extenstion;
                $file_path = $file -> storeAs('images', $new_file_name, 'public');

                // set the new image path as image value of the product
                $item->image = $file_path;

            }
            // save to db
            $item->update([
            'brand_name' => $request->input('brand-name'),
            'model_name' => $request->input('model-name'),
            'category_id' => $request->input('category'),
            'serial_number' => $request->input('serial-number'), 
            'item_status_id' => $request->input('item-status'),
            'description' => $request->input('description')
            ]);

            $request->session()->flash('success', 'Item updated successfully.');

        return redirect(route('items.edit', ['item'=>$item->id]));

        }
    }
    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Item  $item
     * @return \Illuminate\Http\Response
     */
    public function destroy(Item $item)
    {

        $this->authorize('isAdmin');

        $item->delete();
        Storage::delete('public/'.$item->image);

        return redirect(route('items.index'))->with('info', 'Item deleted successfully.');

    }
}

resources/views/items/create.blade.php
@extends('layouts.app')

@section('content')
<h2 class="text-center">{{ isset($item) ? 'Edit Item' : 'Add Items' }}</h2>
<div class="row">
    <div class="col-12 col-md-8 mx-auto">
        <form action="{{ isset($item) ?  route('items.update', $item->id) : route('items.store') }}" method="POST" enctype="multipart/form-data">
            @csrf

            @if(isset($item))
                @method('PUT')
            @endif

            <div class="form-group">
                <label for="brand-name">Brand Name:</label>
                <input type="text" name="brand-name" id="brand-name" class="form-control
                @if($errors->has('brand-name'))
                is-invalid
                @endif
                " value="{{ isset($item) ? $item->brand_name : ''}}">
                <div class="invalid-feedback">{{ $errors->first('brand-name') }}</div>
            </div>
            
            <div class="form-group">
                <label for="model-name">Model Name:</label>
                <input type="text" name="model-name" id="model-name" class="form-control
                @if($errors->has('model-name'))
                is-invalid
                @endif
                " value="{{ isset($item) ? $item->model_name : ''}}">
                <div class="invalid-feedback">{{ $errors->first('model-name') }}</div>
            </div>

            <div class="form-group">
                <label for="category">Category:</label>
                <select class="custom-select
                @if($errors->has('category'))
                is-invalid
                @endif
                " name="category" id="category">
                    @foreach ($categories as $category)
                        <option value="{{ $category->id }}"
                            @if(isset($item))
                            @if($item->category_id === $category->id)
                                selected 
                            @endif
                            @endif
                        >{{ $category->name }}</option>
                    @endforeach
                </select>
                <div class="invalid-feedback">{{ $errors->first('category') }}</div>
            </div>
            
            <div class="form-group">
                <label for="serial-number">Serial #:</label>
                <input type="text" name="serial-number" id="serial-number" class="form-control
                @if($errors->has('serial-number'))
                is-invalid
                @endif
                " value="{{ isset($item) ? $item->serial_number : ''}}"
                >
                <div class="invalid-feedback">{{ $errors->first('serial-number') }}</div>
            </div>
            
            <div class="form-group">
                <label for="description">Description:</label>
                <textarea name="description" id="description" cols="10" rows="5" class="form-control
                @if($errors->has('description'))
                is-invalid
                @endif
                ">{{ isset($item) ? $item->description : '' }}</textarea>
                <div class="invalid-feedback">{{ $errors->first('description') }}</div>
            </div>

            @if(isset($item))
            <div>
                <img src="{{ asset('public/'.$item->image) }}" class="img-thumbnail" style="max-width:300px">
            </div>
            @endif

            <div class="form-group">
                <div class="custom-file">
                    <label for="image">Image:</label>
                    <input type="file" name="image" id="image" class="
                    @if($errors->has('image'))
                    is-invalid
                    @endif
                    ">
                    <div class="invalid-feedback">{{ $errors->first('image') }}</div>
                </div>
            </div>
            
            <div class="form-group">
                <label for="item-status">Status:</label>
                <select class="custom-select
                @if($errors->has('item-status'))
                is-invalid
                @endif
                " name="item-status" id="item-status">
                    @foreach ($item_statuses as $item_status)
                        <option value="{{ $item_status->id  }}"
                            @if(isset($item))
                                @if($item->item_status_id === $item_status->id)
                                    selected 
                                @endif
                            @endif
                        >{{ $item_status->name }}</option>
                    @endforeach
                    
                </select>
                <div class="invalid-feedback">{{ $errors->first('item-status') }}</div>
            </div>

            <button class="btn btn-success float-right">{{ isset($item) ? 'Update Item' : 'Add Item' }}</button>
        </form>
        @if(isset($item))
        <form action="{{ route('items.destroy', $item->id) }}" method="POST">
            @csrf
            @method('DELETE')
            <button class="btn btn-danger float-right mx-3">Delete Item</button>
        </form>
        @endif
    </div>
</div>

@endsection

resources/views/items/index.blade.php
@extends('layouts.app')

@section('content')

<h2 class="text-center">Equipment List</h2>
@can('isAdmin')
<div class="row">
    <div class="col-10 d-flex justify-content-end">
        <ul class="nav">
            <li class="nav-item dropdown show">
                <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="true">Category Filter</a>
                <div class="dropdown-menu" x-placement="bottom-start" style="position: absolute; will-change: transform; top: 0px; left: 0px; transform: translate3d(0px, 35px, 0px);">
                    @foreach($categories as $category)
                        <a class="dropdown-item" href="{{ route('items.index', ['category' => $category->id]) }}">{{$category->name}}</a>
                    @endforeach
                </div>
            </li>
        </ul>
    </div>
    <div class="col-2 d-flex justify-content-end">
        <div>
            <a href="{{ route('items.create') }}" class="btn btn-success ml-3 mb-3">Add Item</a>
        </div>
    </div>
</div>
@endcan

<div class="row">
    <div class="col-12 col-md-12 mx-auto">
        @if($items->count() > 0)
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>Photo</th>
                    <th>Brand</th>
                    <th>Model</th>
                    <th>Category</th>
                    <th>Description</th>
                    <th>Serial #</th>
                    <th>Status</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach($items as $item)
                <tr>
                    <td>
                        <img src="{{ url('public/'.$item->image) }}" class="img-thumbnail" style="max-width:100px">
                    </td>
                    <td>{{ $item->brand_name }}</td>
                    <td>{{ $item->model_name }}</td>
                    <td>{{ $item->category_id ? $item->category->name : 'none'}}</td>
                    <td>{{ $item->description }}</td>
                    <td>{{ $item->serial_number }}</td>
                    <td>{{ $item->item_status_id ? $item->item_status->name : 'none' }}</td>
                    <td>
                        @cannot('isAdmin')
                        <a href="{{ route('items.show', $item->id) }}" class="btn btn-primary btn-sm my-3 {{$item->item_status_id != 1 ? 'disabled' : ''}}" >Borrow this</a>
                        @endcannot
                        <form>
                            @csrf
                            @method('PUT')
                            @can('isAdmin')
                            <a href="{{ route('items.edit', $item->id) }}" class="btn btn-info btn-sm">Edit</a>
                            @endcan
                        </form>
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
        @else
        <h3>No items yet.</h3>
        @endif
    </div>
</div>

@endsection

resources/views/items/show.blade.php
@extends('layouts.app')

@section('content')
{{-- {{ dd(Session::all()) }} --}}
<h2 class="text-center mb-3">Add to Crate</h2>
<div class="row">
	<div class="col-6 text-center">
		<img src="{{ url('public/'.$item->image) }}" class="img-thumbnail w-25 mb-3">
		<h4>{{ $item->brand_name }} {{$item->model_name}}</h4>
		<p>{{ $item->description }}</p>
		<p>Serial #: {{ $item->serial_number }}</p>
		<p>Status: {{ $item->item_status_id ? $item->item_status->name : 'none' }}</p>
	</div>

	<div class="col-6">
		<form action="{{ route('crates.store') }}" method="POST">
			@csrf
			<input type="hidden" name="id" value="{{ $item->id }}">
			<div class="form-group">
				<label for="borrow-date">Borrow Date and Time:</label>
				<input type="borrow-date" name="borrow-date" id="borrow-date" class="form-control
				@if($errors->has('borrow-date'))
                is-invalid
                @endif
				">
				<div class="invalid-feedback">{{ $errors->first('borrow-date') }}</div>
			</div>

			<div class="form-group">
				<label for="return-date">Return Date and Time:</label>
				<input type="return-date" name="return-date" class="form-control
				@if($errors->has('return-date'))
                is-invalid
                @endif
				" id="return-date">
				<div class="invalid-feedback">{{ $errors->first('return-date') }}</div>
			</div>
			<button class="btn btn-success">Add to Crate</button>
		</form>
	</div>
</div>


@endsection

@section('scripts')
	<script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
	<script>
		flatpickr('#borrow-date', {
		    enableTime: true,
		    dateFormat: "Y-m-d H:i",
		})

		flatpickr('#return-date', {
		    enableTime: true,
		    dateFormat: "Y-m-d H:i",
		})
	</script>
@endsection

@section('css')
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
@endsection